### ISSUE TITLE
Update to Vampire coast map

### ISSUE THREAD

**Issue by lodge87** [IMRZ/tww-interactive-map#1]
Hi is there a chance you could update this to the latest Mortal empires map? It's great work and I often use it to have a look before starting a new campaign or to discuss things on reddit.

**Comment by IMRZ** [comment]
Hi @lodge87,

I just did a quick update of the mortal empires map, all the new factions should be visible now. Its still missing some settlements, I will update the rest and the vortex map in the weekend when I have a bit more time.

Wasn't really updating the map since I wasn't sure if anybody was using it hehe. I'm personally only really using the chokepoints overlay at the moment.

If you want to see the new changes right away, you need to visit the app once, wait a bit (15 secs) to load the assets in the backgound and then **close the browser** not just the tab. It's a bit janky at the moment sorry.

Thanks.

**Comment by lodge87** [comment]
Thanks for updating and creating it. I think there are a few people who do use it. For the appreciation check out: https://www.reddit.com/r/totalwar/comments/aqigaa/interactive_map/
